name: FastAPI Book Project CD pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy Application vis ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIV_KEY }}
          script: |
            cd /home/ubuntu/fastapi-app &&
            git pull origin main &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            sudo systemctl restart fastapi-app &&
            sudo systemctl restart nginx